baseURL = "https://fridamariejoergensen.github.io/CSS_project/"
title = "The Network of Harry Potter Characters"
description = "This is the web page explaining the results of an investigation of the Harry Potter universe."
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Frida Marie Jørgensen", "Cecilie Dahl Hvilsted", "Marie Juhl Jørgensen"]
    notebook = "/explainer-notebook.html"
    data = "https://harrypotter.fandom.com/wiki/Main_Page"
    github = "https://github.com/fridamariejoergensen/CSS_project"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

